=== FabioRos/Tecweb/data/XMLS/PostsFabio.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema" targetNamespace = "http://www.musicbreak.com" xmlns = "http://www.musicbreak.com" elementFormDefault = "qualified">

<xsd:element name="posts" type="TPosts" />

<xsd:complexType name="TPosts">
    <xsd:sequence>
        <xsd:element name="eventi" type="TEventi" maxOccurs = "1" />
        <xsd:element name="recensioni" type="TRecensioni" maxOccurs = "1" />
        <xsd:element name="interviste" type="TEventi" maxOccurs = "1" />
        <xsd:element name="news" type="TNews" maxOccurs = "1" />
    </xsd:sequence>
</xsd:complexType>

<!-- Tcommon contiene gli elementi comuni -->
<xsd:complexType name="Tcommon">
    <xsd:sequence>
        <xsd:element name="titolo" type="xsd:string" />
        <xsd:element name="foto" type="xsd:string" />
        <xsd:element name="excerpt" type="TExcerpt" />
        <xsd:element name="descrizione" type="TDescrizione" />
        <xsd:element name="autore" type="TAutore" />
        <xsd:element name="data" type="TData" />
    </xsd:sequence>
</xsd:complexType>


<xsd:complexType name="TEventi">
    <xsd:sequence>
        <xsd:element name="evento" type="TEvento" maxOccurs="unbounded" />
    </xsd:sequence>
</xsd:complexType>



<xsd:complexType name="TEvento">
  <xsd:complexContent>
    <xsd:extension base="Tcommon">
      <xsd:sequence>
        <xsd:element name="dataEvento" type="TData"/>
        <xsd:element name="NumGiorni" type="xsd:positiveInteger" minOccurs="0"/>
        <xsd:element name="luogo" type="xsd:string"/>
        <xsd:element name="oraInizio" type="xsd:string"/>
        <xsd:element name="oraFine" type="xsd:string"/>
        <xsd:element name="indirizzo" type="xsd:string"/>
        <xsd:element name="prezzo" type="xsd:string"/>
        <xsd:element name="email" type="xsd:string"/>
        <xsd:element name="telefono" type="xsd:string"/>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
  <xsd:attribute name="id" type="xsd:string" use="required" />
</xsd:complexType>


</xsd:schema>

=== FabioRos/Tecweb/data/XML/PostsFabio.xml
<?xml version="1.0" encoding="UTF-8"?>
<posts xmlns="http://www.musicbreak.com" 
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
       xs:schemaLocation="http://www.musicbreak.com  ../data/XML/XMLS/PostsFabio.xsd">
   
    <!-- EVENTI -->
    <eventi>
        <evento id="e1">
            <titolo>Sixty party</titolo>
            <foto>../../public_html/img/eventi/sixtyparty.jpg</foto>
            <excerpt>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec purus tempor, semper elit sit amet, congue massa. Nullam luctus sit amet nibh eget dapibus.</excerpt>
            <descrizione>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec purus tempor, semper elit sit amet, congue massa. Nullam luctus sit amet nibh eget dapibus. Nullam massa magna, vestibulum vel bibendum sodales, facilisis sed dui. Duis suscipit velit vestibulum diam eleifend pretium. Aliquam iaculis orci vitae purus gravida, at suscipit ante adipiscing. Nulla sit amet gravida massa. Aenean pharetra diam orci, in dapibus tortor elementum eu. Aenean quam tortor, venenatis ac lacinia ac, aliquam vel turpis. Sed libero quam, tempus sed orci sed, feugiat egestas lacus. Integer aliquam quam mi, ut aliquam felis rutrum ut. Donec accumsan viverra tortor, et gravida felis dictum non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ante justo, sollicitudin ac nunc at, lacinia sagittis mi. Etiam adipiscing dolor id nisl dictum, sit amet facilisis nisi congue. Quisque eget massa ut augue suscipit rhoncus at vitae odio.
            </descrizione>
            <data>04 Agosto 2014</data>
            
            <dataEvento>04 Agosto 2014</dataEvento>
            <luogo>Roma</luogo>
            <oraInizio>22.00</oraInizio>
            <oraFine>02.00</oraFine>
            <indirizzo>via IV Novembre, 4 00100 Roma</indirizzo>
            <prezzo>€11.00</prezzo>
            <email>info@sixtyparty.com</email>
            <telefono>0039 333445566</telefono>
        </evento>
    </eventi>
    
    <!-- RECENSIONI -->
    <recensioni>
        <recensione id="r1">
            <titolo>Bonobo : Late Night Tales</titolo>
            <foto>../../public_html/img/recensioni/sixtyparty.jpg</foto>
            <excerpt> Come un’amore a distanza che, coltivato a lungo e bramato all’inverosimile, finalmente sfocia nel tanto agognato incontro definitivo, la trentatreesima uscita della collana LateNightTales rappresenta la congiunzione perfetta tra due entità fatte praticamente l’una per l’altra e che, sommandosi, scrivono un finale annunciato sin da quando Simon Green ha iniziato ad ottenere il successo che gli spetta.</excerpt>            
            <descrizione>
                Come un’amore a distanza che, coltivato a lungo e bramato all’inverosimile, finalmente sfocia nel tanto agognato incontro definitivo, la trentatreesima uscita della collana LateNightTales rappresenta la congiunzione perfetta tra due entità fatte praticamente l’una per l’altra e che, sommandosi, scrivono un finale annunciato sin da quando Simon Green ha iniziato ad ottenere il successo che gli spetta.Come un’amore a distanza che, coltivato a lungo e bramato all’inverosimile, finalmente sfocia nel tanto agognato incontro definitivo, la trentatreesima uscita della collana LateNightTales rappresenta la congiunzione perfetta tra due entità fatte praticamente l’una per l’altra e che, sommandosi, scrivono un finale annunciato sin da quando Simon Green ha iniziato ad ottenere il successo che gli spetta.Come un’amore a distanza che, coltivato a lungo e bramato all’inverosimile, finalmente sfocia nel tanto agognato incontro definitivo, la trentatreesima uscita della collana LateNightTales rappresenta la congiunzione perfetta tra due entità fatte praticamente l’una per l’altra e che, sommandosi, scrivono un finale annunciato sin da quando Simon Green ha iniziato ad ottenere il successo che gli spetta.
            </descrizione>
            <autore>Fabio Ros</autore>
            <data>04 Dicembre 2013</data>
        </recensione>
        
    </recensioni>
    
    <!-- INTERVISTE -->
    <interviste>
        <intervista id="i1">
            <titolo>Noemi: "Sanremo, The Voice e un nuovo disco. Dopo Londra, sono pronta per rimettermi in gioco"</titolo>
            <foto>../../public_html/img/interviste/noemi.jpg</foto>
            <excerpt>Sanremo, The Voice e il nuovo disco. Un anno intenso per la rossa Noemi, che in attesa di salire sul palco dell'Ariston ci parla di sé e dei suoi mille impegni. Made in London, che uscirà il prossimo 20 febbraio, è il nuovo album di Noemi.</excerpt>
            <descrizione>
                Sanremo, The Voice e il nuovo disco. Un anno intenso per la rossa Noemi, che in attesa di salire sul palco dell'Ariston ci parla di sé e dei suoi mille impegni. Made in London, che uscirà il prossimo 20 febbraio, è il nuovo album di Noemi.Sanremo, The Voice e il nuovo disco. Un anno intenso per la rossa Noemi, che in attesa di salire sul palco dell'Ariston ci parla di sé e dei suoi mille impegni. Made in London, che uscirà il prossimo 20 febbraio, è il nuovo album di Noemi.Sanremo, The Voice e il nuovo disco. Un anno intenso per la rossa Noemi, che in attesa di salire sul palco dell'Ariston ci parla di sé e dei suoi mille impegni. Made in London, che uscirà il prossimo 20 febbraio, è il nuovo album di Noemi.
            </descrizione>
            <data>04 Dicembre 2013</data>
            <autore>Fabio Ros</autore>
        </intervista>
    </interviste>
    
    <!-- NEWS -->
        
    <news>
        <item id="n1">
            <titolo>Richard Benson uno Svitato!</titolo>
            <foto>../../public_html/img/news/richardbenson.jpg</foto>
            <excerpt>Per tastare il polso alla giovane scena rock ravennate abbiamo fatto una chiacchierata con due componenti del quartetto ravennate Actionmen, Matteo Pozzi e Diego Pasini, rispettivamente chitarra/voce e basso di una band completata da Ram Das Libero Foschi (chitarra e voce) e Mattia “Pinna” De Paoli (batteria).Per chi non li conoscesse, gli Actionmen sono un gruppo che suona principalmente pezzi punk-rock e sono conosciuti anche all'estero. Il loro debutto – l'album The Game (2005) pubblicato da Unicorn Records – gli ha dato l'opportunità di emergere e farsi conoscere da un pubblico eterogeneo.</excerpt>
            <descrizione>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec purus tempor, semper elit sit amet, congue massa. Nullam luctus sit amet nibh eget dapibus. Nullam massa magna, vestibulum vel bibendum sodales, facilisis sed dui. Duis suscipit velit vestibulum diam eleifend pretium. Aliquam iaculis orci vitae purus gravida, at suscipit ante adipiscing. Nulla sit amet gravida massa. Aenean pharetra diam orci, in dapibus tortor elementum eu. Aenean quam tortor, venenatis ac lacinia ac, aliquam vel turpis. Sed libero quam, tempus sed orci sed, feugiat egestas lacus. Integer aliquam quam mi, ut aliquam felis rutrum ut. Donec accumsan viverra tortor, et gravida felis dictum non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ante justo, sollicitudin ac nunc at, lacinia sagittis mi. Etiam adipiscing dolor id nisl dictum, sit amet facilisis nisi congue. Quisque eget massa ut augue suscipit rhoncus at vitae odio.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec purus tempor, semper elit sit amet, congue massa. Nullam luctus sit amet nibh eget dapibus. Nullam massa magna, vestibulum vel bibendum sodales, facilisis sed dui. Duis suscipit velit vestibulum diam eleifend pretium. Aliquam iaculis orci vitae purus gravida, at suscipit ante adipiscing. Nulla sit amet gravida massa. Aenean pharetra diam orci, in dapibus tortor elementum eu. Aenean quam tortor, venenatis ac lacinia ac, aliquam vel turpis. Sed libero quam, tempus sed orci sed, feugiat egestas lacus. Integer aliquam quam mi, ut aliquam felis rutrum ut. Donec accumsan viverra tortor, et gravida felis dictum non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ante justo, sollicitudin ac nunc at, lacinia sagittis mi. Etiam adipiscing dolor id nisl dictum, sit amet facilisis nisi congue. Quisque eget massa ut augue suscipit rhoncus at vitae odio.
            </descrizione>
            <data>20 Gennaio 2014</data>
            <autore>Alberto Andeliero</autore>
        </item>
    </news>
   
   
</posts>
