=== FabioRos/Tecweb/data/XMLS/TagsPosts.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema" targetNamespace = "http://www.musicbreak.com" xmlns = "http://www.musicbreak.com" elementFormDefault = "qualified">
    <xsd:element name="TagsPosts" type="TTagsPosts" />

    <xsd:complexType name="TTagsPosts">
        <xsd:sequence>
            <xsd:element name="corrispondenza" type="TCorrispondenza" maxOccurs = "unbounded" />
        </xsd:sequence>
    </xsd:complexType>
              
    <xsd:complexType name="TCorrispondenza">
        <xsd:sequence>
            <xsd:element name="idTag" type="xsd:positiveInteger" minOccurs="1" maxOccurs="1" />
            <xsd:element name="idPost" type="xsd:positiveInteger" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== FabioRos/Tecweb/data/XML/TagsPosts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Questo file serve per mettere in relazione le gallerie con i post 
(di tipo intervista) a cui sono collegati.
-->
<TagsPosts xmlns="http://www.musicbreak.com" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
           xs:schemaLocation="http://www.musicbreak.com/data/XML/XMLS TagsPosts.xsd">
    <corrispondenza>
        <idTag>1</idTag>
        <idPost>2</idPost>
    </corrispondenza>
    
    <corrispondenza>
        <idTag>4</idTag>
        <idPost>2</idPost>
    </corrispondenza>
    
    <corrispondenza>
        <idTag>3</idTag>
        <idPost>2</idPost>
    </corrispondenza>
    
    <corrispondenza>
        <idTag>2</idTag>
        <idPost>3</idPost>
    </corrispondenza>
</TagsPosts>
